version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis

  mosquitto:  
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes: 
      - ./mosquitto:/mosquitto/config

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: med
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: medicoes
    volumes:
      - datapostgres:/var/lib/postgresql/data

volumes:
  redis:
  mosquitto:
  datapostgres:
